### ISSUE TITLE
Exercise instructs user to write code that already exists

### ISSUE THREAD

**Issue by steveandroulakis** [temporalio/edu-interacting-with-workflows-go-code#6]
https://github.com/temporalio/edu-interacting-with-workflows-go-code/blob/ee9151152520df7683b0b17076be753555bf3459/exercises/sending-signals-external/practice/workflow.go#L15

The Interacting With Workflows course and the linked comment give instructions to create a struct, but that struct already exists (above)? Perhaps I'm missing something in my understanding?

**Comment by axfelix** [comment]
Nope, this was an oversight on my part — forgot to remove that snippet of working code from the solution when I was creating this practice exercise :) 

Fixed in https://github.com/temporalio/edu-interacting-with-workflows-go-code/commit/5929b96489497d0876c862290dd696c20a07cdb2
